# Generated by Django 3.2.3 on 2021-09-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_clientsfromtg_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='status',
            field=models.CharField(default='vacant', max_length=30),
        ),
    ]
