# Generated by Django 3.2.3 on 2021-09-27 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_clients_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='toning',
            field=models.CharField(default='без тонировки', max_length=20),
        ),
        migrations.AddField(
            model_name='cars',
            name='year_of_issue',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='order_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rent',
            name='order_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='clients',
            name='passport_series',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='bot_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='url_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
