# Generated by Django 3.2.3 on 2021-09-28 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20210928_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.orders')),
            ],
            options={
                'verbose_name': 'OrderInformation',
                'verbose_name_plural': 'OrdersInformation',
            },
        ),
    ]
