# Generated by Django 3.2.3 on 2021-09-28 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_orderinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_extended',
            field=models.BooleanField(default=False),
        ),
    ]
