# Generated by Django 3.2.3 on 2021-09-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_orders_is_extended'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinformation',
            name='order_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
