# Generated by Django 3.2.3 on 2021-09-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_orderinformation_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='extended_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
