# Generated by Django 3.2.3 on 2021-09-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_orders_extended_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='year_of_issue',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
