# Generated by Django 3.2.3 on 2021-09-30 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_auto_20210930_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='rent_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.rent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cars',
            name='rent_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.rent'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientsfromtg',
            name='rent_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crm.rent'),
            preserve_default=False,
        ),
    ]
